package view;

import customModel.HoaDonDoanhThu;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HoaDonChiTiet;
import model.ModelCard;
import service.ICTSPService;
import service.impl.HDCTImpl;
import service.IHDCTService;
import service.impl.CTSPImpl;

/**
 *
 * @author fallinluv2003
 */
public class TestThongKe extends javax.swing.JFrame {

    private IHDCTService hdctSer = new HDCTImpl();
    private ICTSPService ctspSer = new CTSPImpl();
  

    public TestThongKe() {
        initComponents();
        List<HoaDonDoanhThu> list = hdctSer.getDoanhSo();
        loadTableDoanhSo(list);
        initCardData();
    }

    private void initCardData() {
        card1.setData(new ModelCard("Sản phẩm đang kinh doanh", ctspSer.getProduct().toString(), 20, null));
        card2.setData(new ModelCard("Sản phẩm ngừng kinh doanh", ctspSer.getNonProduct().toString(), 0, null));
        card3.setData(new ModelCard("Tổng số lượng sản phẩm", ctspSer.getSumProduct().toString(), 95, null));
        card4.setData(new ModelCard("Sản phẩm sắp hết hàng", ctspSer.getOutProduct().toString(), 10, null));
    }

    // Thêm TestThongKe
    void loadTableDoanhSo(List<HoaDonDoanhThu> list) {
        DefaultTableModel model = (DefaultTableModel) tbDoanhSo.getModel();
        model.setRowCount(0);
        for (HoaDonDoanhThu x : list) {
            model.addRow(new Object[]{
                x.getMaCTSP(), x.getTenSP(), x.getTenDm(), x.getTenCL(), x.getTenMau(), x.getTenNSX(), x.getSoLuongBanRa()
            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDoanhSo = new com.raven.suportSwing.TableColumn();
        card1 = new component.Card();
        card2 = new component.Card();
        card3 = new component.Card();
        card4 = new component.Card();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbDoanhSo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Danh Mục", "Chất liệu", "Màu", "NSX", "Số lượng bán ra"
            }
        ));
        jScrollPane1.setViewportView(tbDoanhSo);
        if (tbDoanhSo.getColumnModel().getColumnCount() > 0) {
            tbDoanhSo.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(TestThongKe.class, "TestThongKe.tbDoanhSo.columnModel.title0")); // NOI18N
            tbDoanhSo.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(TestThongKe.class, "TestThongKe.tbDoanhSo.columnModel.title1")); // NOI18N
            tbDoanhSo.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(TestThongKe.class, "TestThongKe.tbDoanhSo.columnModel.title3")); // NOI18N
            tbDoanhSo.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(TestThongKe.class, "TestThongKe.tbDoanhSo.columnModel.title4")); // NOI18N
            tbDoanhSo.getColumnModel().getColumn(4).setHeaderValue(org.openide.util.NbBundle.getMessage(TestThongKe.class, "TestThongKe.tbDoanhSo.columnModel.title5")); // NOI18N
            tbDoanhSo.getColumnModel().getColumn(5).setHeaderValue(org.openide.util.NbBundle.getMessage(TestThongKe.class, "TestThongKe.tbDoanhSo.columnModel.title6")); // NOI18N
            tbDoanhSo.getColumnModel().getColumn(6).setHeaderValue(org.openide.util.NbBundle.getMessage(TestThongKe.class, "TestThongKe.tbDoanhSo.columnModel.title2")); // NOI18N
        }

        card1.setColorGradient(new java.awt.Color(211, 28, 215));

        card2.setColorGradient(new java.awt.Color(72, 111, 252));

        card3.setBackground(new java.awt.Color(194, 85, 1));
        card3.setColorGradient(new java.awt.Color(255, 212, 99));

        card4.setBackground(new java.awt.Color(60, 195, 0));
        card4.setColorGradient(new java.awt.Color(208, 255, 90));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(card1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(card2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(card3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(card4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(card1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.Card card1;
    private component.Card card2;
    private component.Card card3;
    private component.Card card4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.raven.suportSwing.TableColumn tbDoanhSo;
    // End of variables declaration//GEN-END:variables

}
